apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: python-app-3
  description: Python app that displays the time
  annotations:
    github.com/project-slug: anthony-gilbert/python-app-3
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: development
  lifecycle: experimental
